name: Deploy Website to AWS

on:
  push:
    branches:
      - main  # This triggers the robot every time you push to GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub starts a fresh Linux machine for you

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Copies your files onto the Linux machine

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 

      - name: Sync to S3
        run: |
          aws s3 sync . s3://my-first-cloud-site-akram --delete --exclude ".github/*"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id E1BW1G2B2OZR9C --paths "/*"